import React from 'react';
import {Link} from 'react-router-dom';
import {PageHead,Notice,PlaceCard,Stamp} from '../components/shared.jsx';
import {places,areas} from '../data/catalog.js';
import {firstVisitPlaces,airportGuides,airportTransferChoices,areaGuides,openFacts,contentDate,licenseUrl,wikidataPolicy} from '../data/first-visit.js';
export function External({href,children}){return <a className="text-link" href={href} target="_blank" rel="noopener noreferrer">{children}</a>;}
export function Evidence({fact}){return <div className="evidence"><b>資料來源與使用範圍</b><p>名稱、概略座標與網站欄位：<External href={fact.url}>Wikidata {fact.id}</External> · <External href={licenseUrl}>CC0 1.0</External></p><p className="fine">來源核對 {fact.retrievedAt} · 資料版本 {fact.revision}。社群資料可能有誤；來源核對不等於營業、票價或入場規定已確認。規劃建議由本站撰寫，非官方背書。</p></div>;}
export function AirportGuideContent({id}){const a=airportGuides[id],fact=openFacts[a.qid],site=fact.props.P856[0]?.value;return <><Notice>已補入機場名稱與機場碼的開放資料。交通服務、航廈、票價、乘車位置與班次仍需查當期官方公告。</Notice><div className="grid two"><section className="panel"><h2>先核對這座機場</h2><p>{fact.labels.en} · 機場碼 {fact.props.P238[0]?.value}</p><p>{a.note}</p><p>不要只用航空公司是廉航或傳統航空來推測機場；以你的機票為準。</p>{site&&<External href={site}>開啟 Wikidata 所列機場網站</External>}<p className="fine">此連結來自開放資料，本站未擷取機場網站內容或確認所有最新公告。</p><Evidence fact={fact}/></section><section className="panel"><h2>進市區怎麼選？</h2><h3>{a.rail}：先核對的候選交通</h3><p>{a.railAdvice}</p><p>若深夜抵達、同行需要協助或行李多，可同時比較計程車與預約接送。車資之外，確認機場附加、過路費、等待費是否計入。</p><p>把「出關與領行李 → 等車 → 進城 → 住宿辦理入住」分開預留，不把飛機落地時間當成能開始逛景點的時間。</p><Link className="button secondary" to="/travel/transportation">查看交通選擇指南</Link></section></div><section className="panel"><h2>抵達／回程檢查清單</h2><ol><li>核對機場碼、日期與曼谷當地時間。</li><li>把住宿的完整地址與地圖位置離線保存。</li><li>回程先查航空公司報到截止及機場當期指示，再安排最後一天；本站緩衝估算不是航空公司規定。</li><li>如果去回程機場不同，分別核對交通，不套用同一路線。</li></ol><div className="button-row"><Link className="button" to="/planner">安排抵達與離開日</Link>{id==='bkk'&&<Link className="button secondary" to="/lounges">BKK 貴賓室（資料待確認）</Link>}</div></section></>;}
export function AirportComparison(){return <section className="panel"><h2>先看機票上的 BKK 或 DMK</h2><p>曼谷的兩個機場分開規劃；先核對去程及回程機場，再選住宿與進城方式。不要以航空公司類型推測機場。</p><div className="grid two">{Object.entries(airportGuides).map(([id,a])=><div key={id}><h3>{a.name}</h3><p>{openFacts[a.qid].labels.en}</p><p>{a.note}</p><Link className="button secondary" to={`/travel/airports/${id}`}>查看機場與交通準備</Link></div>)}</div><p className="fine">名稱與機場碼來源：<External href={openFacts.Q194316.url}>BKK 開放資料</External> · <External href={openFacts.Q1046755.url}>DMK 開放資料</External>（CC0；核對 {contentDate}）。交通公告不包含在基本資料核對中。</p></section>;}
export function TransferGuide(){return <section className="panel"><h2>機場進城：比較完整路程</h2><p>先確定機場、住宿地址、人數、行李與抵達時間，再看下面四種選擇。這是本站原創決策指南；班次、票價與實際接續請從機場網站核對。</p><div className="grid two">{airportTransferChoices.map(c=><article className="info-card" key={c.name}><h3>{c.name}</h3><p>{c.for}</p><p>{c.steps}</p><p><b>費用：</b>{c.cost}</p><p className="fine">{c.risk}</p></article>)}</div><div className="button-row"><Link className="text-link" to="/travel/airports/bkk">BKK 機場資訊入口</Link><Link className="text-link" to="/travel/airports/dmk">DMK 機場資訊入口</Link></div></section>;}
export function AreaAdvice({area}){const a=areaGuides[area];return <><p className="meta">{a.focus}</p><p>{a.why}</p><h2>訂房前核對</h2><p>{a.check}</p><ul><li>每晚完整含稅價格、早餐、取消規定與入住人數。</li><li>航班抵達時能否入住；提早到或退房後能否寄放行李。</li><li>實際地址、車站出口與最後一段步行，不只看平台的區域分類。</li></ul><Stamp item={{status:'本站規劃建議',source:'本專案原創選房比較方法；非飯店營運或價格資料',updatedAt:contentDate,confirmedAt:null}}/></>;}
export default function FirstVisit(){return <div className="container first-visit"><PageHead eyebrow="YOUR FIRST BANGKOK" title="第一次去曼谷，從這份指南開始" description="先選機場與住宿區域，再把真實地點排成自己的旅行。"/><div className="day-tabs"><button type="button" className="chip" onClick={()=>{document.getElementById('airports')?.scrollIntoView();}}>機場與進城</button><button type="button" className="chip" onClick={()=>{document.getElementById('stay')?.scrollIntoView();}}>住哪裡</button><button type="button" className="chip" onClick={()=>{document.getElementById('places')?.scrollIntoView();}}>10 個地點</button><Link className="chip" to="/trips/bangkok-3">三日安排</Link></div><Notice>這一批提供真實地點的基本開放資料與本站撰寫的旅行建議；營業時間、票價、照片及交通班次仍逐項待確認。你可以參考動線與選擇方法，出發前再核對當日公告。</Notice><section id="airports"><AirportComparison/><TransferGuide/></section><section id="stay"><h2>住在哪裡，先看你的行程</h2><p>以下是選房建議，不是飯店推薦或即時房價。</p><div className="grid three">{areas.map(area=><article className="info-card" key={area}><h3>{area}</h3><p>{areaGuides[area].focus}</p><p>{areaGuides[area].why}</p><Link className="text-link" to={`/travel/areas/${encodeURIComponent(area)}`}>查看選房注意事項</Link></article>)}</div></section><section id="places"><h2>10 個可以放進行程的真實地點</h2><p>選你有興趣的地點，詳細頁提供介紹、安排建議、來源與待核對欄位。</p><div className="grid three">{firstVisitPlaces.map(g=><PlaceCard key={g.id} place={places.find(p=>p.id===g.id)}/>)}</div></section><section className="panel"><h2>第一次曼谷：三日動線</h2><p>舊城文化 → 寺廟與公園 → 暹羅藝文與購物。採用真實地點；午餐由你自行選擇，不以虛構餐廳代替推薦。每日抵達時間、交通與預留費用仍為估算。</p><div className="button-row"><Link className="button" to="/trips/bangkok-3">查看三日安排並修改</Link><Link className="button secondary" to="/planner">依自己的偏好排程</Link></div></section><section className="panel"><h2>這些內容從哪裡來？</h2><p>地點名稱、概略座標、機場碼與網站欄位取自 Wikidata CC0 結構化資料。文章、選房建議與行程編排由本專案使用 Codex 協助撰寫；沒有下載外站照片、重製旅遊文章或抓取官方票價。</p><p><External href={wikidataPolicy}>查看資料授權</External> · <Link className="text-link" to="/sources">本站來源與使用說明</Link></p><p className="fine">更新 {contentDate}。CC0 不保證資料正確、商標權或其他權利；Wikidata 與本站都不代表景點營運方。</p></section></div>;}
