import React from 'react';
import {Link} from 'react-router-dom';
import {PageHead,Notice,AddToTrip,Icon} from './shared.jsx';
import {ReferenceCredit} from './ContentReference.jsx';
export function FoodGuideDetail({place:p}){
 const g=p.foodGuide;
 const fact=(label,value)=><React.Fragment key={label}><dt>{label}</dt><dd>{value??'待確認'}<p className="fine">社群指南參考 · 欄位日期：{g.sourceUpdatedAt??'來源未提供'}<br/>來源章節：{g.section} · 閱讀：{g.reviewedAt} · 官方核實：尚未確認</p></dd></React.Fragment>;
 return <div className="container food-guide"><Link className="text-link" to="/travel/food">返回美食列表</Link><PageHead eyebrow={`${p.area} · 餐廳指南參考`} title={p.name} description="先探索想吃的餐點，再核對當日店況與完整路程。"/><Notice>這是社群指南收錄的店家資料，並非已向店家確認的目前營運資訊。可手動加入行程；當期時段、餐費與座標不足時，暫不納入自動排程。</Notice><div className="detail-grid"><section className="panel"><div className="card-visual"><Icon name="food" size={48}/><span>據點照片待授權</span></div><h2>店家與餐點參考</h2><dl className="detail-list">{fact('參考店址',g.address)}{fact('餐點參考',g.dishes)}{fact('交通起點',g.transit)}</dl><ReferenceCredit sources={[g.source]}/><h2>到店前核對</h2><dl className="detail-list"><dt>營業／公休日</dt><dd>待確認；不採用缺乏時效依據的舊時段。</dd><dt>餐費／價格區間</dt><dd>待確認；不將舊列價當作目前售價或免費。</dd><dt>資料日期</dt><dd>{g.sourceUpdatedAt??'來源未提供欄位更新日期'}；閱讀日期不是店家確認日期。</dd><dt>官方網站／社群</dt><dd>待確認；未填入推測或未核對的網址。</dd><dt>座標／入口／無障礙</dt><dd>待確認；沒有使用猜測座標。</dd><dt>停留建議</dt><dd>{p.duration} 分鐘（本站規劃建議，未包含已確認排隊時間）。</dd></dl><p className="fine">尚未採用當期價格、營業公告、米其林資格或旅客評價；來源有權重用不代表內容仍然有效。</p></section><aside><section className="panel"><h2>安排這一餐</h2><p>{g.planning}</p><AddToTrip place={p}/><p className="fine">餐費會以「待確認」加入，請自行填入預留額；不是零成本。排程工具的可編輯時段不是店家營業時間。</p><a className="text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.name.split('｜')[0]} ${g.address} Bangkok`)}`} target="_blank" rel="noopener noreferrer">在外部地圖核對店名與位置</a><p className="fine">只由你點擊後開啟外部搜尋；本站不取得地圖結果或你的定位。</p><Link className="text-link" to="/travel/transportation">查看交通指南</Link></section><section className="panel"><h2>用餐準備</h2><p>向店家確認辣度、食材與份量；有飲食限制時，先取得店家的明確答覆。預留選店、等候及休息時間。</p><p className="fine">以上為本站規劃建議；沒有宣稱此店符合過敏、素食、宗教或無障礙需求。</p></section></aside></div></div>;
}
