import React, {createContext,useContext,useState,useEffect,useRef} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {places,updatedAt} from '../data/catalog.js';
import {readTrips,writeTrips,duplicateTrip,STORE_KEY,DRAFT_KEY,readDraft} from '../services/trip-storage.js';
import {recalculateTrip,blankTrip,makeActivity} from '../services/planner.js';
export const AppContext=createContext(null);
export const useApp=()=>useContext(AppContext);
export const money=n=>Number.isFinite(n)?`${Math.round(n).toLocaleString('zh-TW')} THB`:'待確認';
export function download(name,value){const raw=typeof value==='string'?value:JSON.stringify(value,null,2);window.dispatchEvent(new CustomEvent('bangkok-export',{detail:{name,raw}}));}
function ExportDialog({data,onClose}){const dialog=useRef(null),backupField=useRef(null),[url,setUrl]=useState(''),[message,setMessage]=useState('');useEffect(()=>{if(!data)return;const link=URL.createObjectURL(new Blob([data.raw],{type:'application/json;charset=utf-8'}));setUrl(link);setMessage('');dialog.current.showModal();return()=>URL.revokeObjectURL(link);},[data]);if(!data)return null;return <dialog ref={dialog} className="export-dialog" onCancel={onClose} aria-labelledby="export-title"><h2 id="export-title">行程備份已準備好</h2><p>點選下載，將檔案留存在你的裝置中。若此瀏覽器不支援下載，可複製內容另存成 JSON 檔案。</p><p className="fine">檔名：{data.name} · 約 {Math.ceil(new Blob([data.raw]).size/1024)} KB。備份可能包含行程日期與備註，請自行保管。</p><div className="button-row"><a className="button" href={url} download={data.name}>下載 JSON 檔案</a><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(data.raw);setMessage('備份內容已複製。可貼入文字編輯器並另存為 .json。');}catch{const field=backupField.current;field.closest('details').open=true;field.focus();field.select();if(document.execCommand('copy')){setMessage('備份內容已複製，請另存成 .json 檔案。');return;}setMessage('瀏覽器未允許複製。請在下方選取全部內容，再使用複製功能。');}}}>複製備份內容</button><button className="button secondary" onClick={onClose}>關閉備份視窗</button></div>{message&&<p role="status">{message}</p>}<details><summary>查看備份內容</summary><label className="field"><span>行程 JSON 備份內容</span><textarea ref={backupField} readOnly value={data.raw} rows={10}/></label></details></dialog>;}
export function AppProvider({children}){
 const [trips,setTrips]=useState([]),[storeError,setStoreError]=useState(''),[notice,setNotice]=useState('');
 const [confirmation,setConfirmation]=useState(null);const ask=(message,action,label='確認操作')=>setConfirmation({message,action,label});
 const [exportData,setExportData]=useState(null);useEffect(()=>{const open=e=>setExportData(e.detail);window.addEventListener('bangkok-export',open);return()=>window.removeEventListener('bangkok-export',open);},[]);
 useEffect(()=>{const reload=()=>{try{setTrips(readTrips(localStorage));setStoreError('');}catch(e){setStoreError(`無法讀取本機行程：${e.message}。原始資料沒有被清除。`);}};reload();const f=e=>{if(e.key===STORE_KEY)reload();};window.addEventListener('storage',f);return()=>window.removeEventListener('storage',f);},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(id);},[notice]);
 const save=t=>{try{const current=readTrips(localStorage);const valid=recalculateTrip({...t,updatedAt:new Date().toISOString()},places);const next=[valid,...current.filter(x=>x.id!==t.id)];writeTrips(localStorage,next);setTrips(next);setStoreError('');setNotice('已儲存在目前瀏覽器與裝置。');return true;}catch(e){setTrips(prev=>[t,...prev.filter(x=>x.id!==t.id)]);setNotice(`儲存失敗：${e.message}。請立即匯出備份。`);return false;}};
 const remove=id=>ask('確定刪除此行程與草稿？此操作無法復原，請先匯出備份。',()=>{try{const next=readTrips(localStorage).filter(t=>t.id!==id);writeTrips(localStorage,next);const drafts=JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}');delete drafts[id];localStorage.setItem(DRAFT_KEY,JSON.stringify(drafts));setTrips(next);setNotice('行程已刪除。');}catch(e){setNotice(`刪除失敗：${e.message}`);}},'確認刪除');
 const copy=t=>{const result=duplicateTrip(t);save(result);return result;};
 const clear=()=>ask('清除這個網站的所有本機行程與草稿？此操作無法復原，請先匯出備份。',()=>{try{localStorage.removeItem(STORE_KEY);localStorage.removeItem(DRAFT_KEY);setTrips([]);setStoreError('');setNotice('本機行程已清除。');}catch(e){setNotice(e.message);}},'確認清除');
 return <AppContext.Provider value={{trips,save,remove,copy,notice:setNotice,clear,storeError,confirm:ask}}>{children}<ExportDialog data={exportData} onClose={()=>setExportData(null)}/><ConfirmDialog data={confirmation} onClose={()=>setConfirmation(null)}/>{notice&&<div className="toast" role="status">{notice}<button aria-label="關閉提示" onClick={()=>setNotice('')}>×</button></div>}</AppContext.Provider>;
}
function ConfirmDialog({data,onClose}){const ref=useRef(null);useEffect(()=>{if(data)ref.current.showModal();},[data]);if(!data)return null;return <dialog ref={ref} className="export-dialog" onCancel={onClose} aria-labelledby="confirm-title"><h2 id="confirm-title">請確認這項操作</h2><p>{data.message}</p><div className="button-row"><button className="button secondary" autoFocus onClick={onClose}>取消，保留原內容</button><button className="button danger" onClick={()=>{try{data.action();}finally{onClose();}}}>{data.label}</button></div></dialog>;}
export function Icon({name='pin',size=22}){const paths={pin:<><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18"/></>,plane:<path d="m3 12 7 1 8 8 2-1-5-8 6-7-1-2-7 6-8-5-1 2 8 8-1 7Z"/>,bed:<><path d="M3 19V6m18 13V9M3 15h18M8 8h10a3 3 0 0 1 3 3v4H8Z"/><path d="M3 9h5v6H3"/></>,train:<><rect x="5" y="3" width="14" height="15" rx="4"/><path d="M5 10h14m-11 8-3 3m11-3 3 3M8 14h1m6 0h1"/></>,food:<><path d="M5 3v6m3-6v6M2 3v6a3 3 0 0 0 6 0m-3 3v9m13-18v18m0-18c-5 4-5 9 0 9"/></>,temple:<><path d="M3 21h18M5 19V9h14v10M2 9h20L12 3Zm6 10v-5h8v5"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,edit:<><path d="m14 5 5 5M4 20l5-1L21 7l-5-5L4 14Z"/></>,wallet:<><rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 9h18m-7 4h7v4h-7Z"/></>,leaf:<><path d="M20 3C8 1 2 9 5 15s14 5 15-12Z"/><path d="m5 20 10-10"/></>,menu:<path d="M4 6h16M4 12h16M4 18h16"/>,bag:<><rect x="5" y="7" width="14" height="14" rx="2"/><path d="M9 7V5a3 3 0 0 1 6 0v2"/></>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.pin}</svg>;}
export function Layout({children}){const [open,setOpen]=useState(false);const location=useLocation();useEffect(()=>{setOpen(false);window.scrollTo(0,0);const privatePage=location.pathname.startsWith('/my-trips');let meta=document.querySelector('meta[name="robots"]');if(!meta){meta=document.createElement('meta');meta.name='robots';document.head.append(meta);}meta.content=privatePage?'noindex,nofollow':'index,follow';document.title=`${location.pathname==='/'?'曼谷自由行旅遊規劃平台':({'first-visit':'首次曼谷指南',planner:'自動排程',lounges:'BKK 貴賓室','my-trips':'我的行程',travel:'旅遊資訊',trips:'推薦行程'}[location.pathname.split('/')[1]]??'探索曼谷')}｜Bangkok Travel Guide`;},[location.pathname]);
 const links=[['/travel','旅遊資訊'],['/trips','推薦行程'],['/lounges','BKK 貴賓室'],['/planner','自動排程']];
 return <><a className="skip" href={`${import.meta.env.BASE_URL}${import.meta.env.MODE==='pages'?'#'+location.pathname+location.search:'#main'}`} onClick={e=>{e.preventDefault();const main=document.getElementById('main');main?.focus();main?.scrollIntoView();}}>跳至主要內容</a><header><div className="nav-inner"><Link to="/" className="brand"><span className="brand-mark"><Icon name="temple" size={26}/></span><span>Bangkok<span className="brand-small">TRAVEL GUIDE</span></span></Link><button className="menu-toggle" aria-label="開啟導覽選單" aria-expanded={open} aria-controls="nav-menu" onClick={()=>setOpen(!open)}><Icon name="menu"/></button><nav id="nav-menu" className={open?'open':''} aria-label="主要導覽">{links.map(([to,label])=><Link key={to} className={location.pathname.startsWith(to)?'active':''} to={to}>{label}</Link>)}<Link className="nav-trip" to="/my-trips"><Icon name="bag" size={18}/> 我的行程</Link></nav></div></header><main id="main" tabIndex={-1}>{children}</main><footer><div className="footer-inner"><div><Link className="footer-brand" to="/">Bangkok Travel Guide</Link><p>Discover Bangkok. Plan Your Journey.</p><p>從探索到出發，把曼谷安排成你的樣子。</p><small>第一版行程儲存在目前瀏覽器與裝置中。</small></div><div><b>探索曼谷</b>{[['flights','機票與機場'],['accommodation','住宿'],['transportation','交通'],['food','美食'],['attractions','觀光']].map(([s,l])=><Link key={s} to={`/travel/${s}`}>{l}</Link>)}</div><div><b>規劃旅程</b><Link to="/first-visit">第一次去曼谷</Link><Link to="/trips">推薦行程</Link><Link to="/planner">自動排程</Link><Link to="/my-trips">我的行程</Link><Link to="/lounges">BKK 貴賓室</Link><Link to="/lounge-finder">信用卡查詢</Link></div><div><b>關於平台</b>{[['about','關於我們'],['faq','常見問題'],['contact','聯絡我們'],['sitemap','網站地圖'],['sources','資料來源'],['privacy','隱私權政策'],['disclaimer','免責聲明']].map(([s,l])=><Link key={s} to={`/${s}`}>{l}</Link>)}</div></div><div className="footer-bottom">© 2026 Bangkok Travel Guide <span>範例、預估與待確認資訊皆有標示；非即時旅遊資料。</span></div></footer></>;}
export function PageHead({eyebrow='BANGKOK TRAVEL GUIDE',title,description,children}){return <div className="page-head"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p>{children}</div>;}
export function Stamp({item,compact=false}){return <div className={`stamp ${compact?'compact':''}`}><span className={`badge ${item.status==='待確認'?'pending':''}`}>{item.status??'待確認'}</span><span>更新 {item.updatedAt??updatedAt} · 查證 {item.confirmedAt??'尚未查證'}</span>{!compact&&<small>來源：{item.source??'資料待確認'}</small>}</div>;}
export function Empty({title='目前沒有符合條件的結果',children}){return <div className="empty"><Icon name="leaf" size={32}/><h3>{title}</h3>{children}</div>;}
export function Notice({children,tone=''}){return <div className={`notice ${tone}`}>{children}</div>;}
export function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function NumberInput({value,onCommit,min=0,max=1000000,allowEmpty=false}){const [raw,setRaw]=useState(value==null?'':String(value));useEffect(()=>setRaw(value==null?'':String(value)),[value]);const app=useApp();return <input type="number" min={min} max={max} step="1" value={raw} onChange={e=>setRaw(e.target.value)} onBlur={()=>{if(raw===''&&allowEmpty){onCommit(null);return;}const n=Number(raw);if(raw===''||!Number.isInteger(n)||n<min||n>max){setRaw(value==null?'':String(value));app.notice(`請輸入 ${min}–${max} 之間的整數。`);return;}onCommit(n);}}/>;}
export function AddToTrip({place}){const app=useApp();const navigate=useNavigate();const [open,setOpen]=useState(false);const [tripId,setTripId]=useState('');const [day,setDay]=useState('0');
 const add=()=>{let trip=app.trips.find(t=>t.id===tripId);if(!trip)trip=blankTrip({start:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Bangkok'}),days:3,people:1,startTime:'09:00',endTime:'20:00'});trip=structuredClone(trip);trip.days[Number(day)]?.activities.push(makeActivity(place));app.save(trip);setOpen(false);navigate(`/my-trips/${trip.id}/edit`);};
 return <><button className="button small" onClick={()=>setOpen(!open)}>加入行程</button>{open&&<div className="inline-panel"><Field label="加入哪份行程"><select value={tripId} onChange={e=>{setTripId(e.target.value);setDay('0');}}><option value="">建立新的 3 天行程</option>{app.trips.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="選擇日期"><select value={day} onChange={e=>setDay(e.target.value)}>{Array.from({length:app.trips.find(t=>t.id===tripId)?.days.length??3},(_,i)=><option key={i} value={i}>第 {i+1} 天</option>)}</select></Field><div className="actions"><button className="button small" onClick={add}>確認加入</button><button className="button secondary small" onClick={()=>setOpen(false)}>取消</button></div></div>}</>;}
export function PlaceCard({place}){const path=place.type==='餐廳'?'food':'attractions';return <article className="place-card"><div className={`card-visual area-${['暹羅','素坤逸','是隆','舊城河岸','唐人街','河岸','洽圖洽'].indexOf(place.area)}`}><Icon name={place.type==='餐廳'?'food':place.type==='購物'?'bag':'temple'} size={42}/><span>{place.area}</span><small>圖片待授權</small></div><div className="card-body"><div className="meta">{place.category} · {place.area}</div><h3><Link to={`/travel/${path}/${place.id}`}>{place.name}</Link></h3><p>停留 {place.duration} 分鐘 · {place.foodGuide?'餐費':place.fact?'費用預留':'範例'} {money(place.cost)}</p>{place.foodGuide&&<p className="fine">{place.foodGuide.dishes} · 營業與位置待確認</p>}{place.fact&&<p className="fine">預留額不是票價；0 不代表免費。停留時間為建議。</p>}<Stamp item={place} compact/><div className="actions"><Link className="text-link" to={`/travel/${path}/${place.id}`}>查看資訊</Link><AddToTrip place={place}/></div></div></article>;}
function PendingLocations({activities}){return activities.length?<Notice tone="warning"><b>{activities.length} 個地點座標待確認，未繪入示意圖</b><ul>{activities.map(a=><li key={a.id}>{a.name} · <a target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${a.name.split('｜')[0]} ${a.snapshot.address??''} Bangkok`)}`}>外部地圖核對位置</a></li>)}</ul><p className="fine">示意圖僅涵蓋有座標的地點，不是完整路線。外部搜尋結果未經本站核實。</p></Notice>:null;}
export function MapView({day}){const pending=day.activities.filter(a=>a.snapshot&&(!Number.isFinite(a.snapshot.lat)||!Number.isFinite(a.snapshot.lng)));const points=day.activities.filter(a=>a.snapshot&&Number.isFinite(a.snapshot.lat)&&Number.isFinite(a.snapshot.lng));if(!points.length)return <><PendingLocations activities={pending}/><Empty title="加入有位置資料的地點後顯示示意圖"/></>;
 const lats=points.map(a=>a.snapshot.lat),lngs=points.map(a=>a.snapshot.lng);const minLat=Math.min(...lats),minLng=Math.min(...lngs),latRange=Math.max(Math.max(...lats)-minLat,.015),lngRange=Math.max(Math.max(...lngs)-minLng,.015);const coords=points.map(a=>({x:45+(a.snapshot.lng-minLng)/lngRange*510,y:290-(a.snapshot.lat-minLat)/latRange*240}));
 return <div className="map-wrap"><PendingLocations activities={pending}/><div className="map-label">每日位置示意圖 <span>非道路導航 · 座標來源依活動資料</span></div><svg className="map" viewBox="0 0 600 340" role="img" aria-label="依座標繪製的每日行程順序示意圖"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="#d5ddd2" strokeWidth=".6"/></pattern></defs><rect width="600" height="340" fill="url(#grid)"/><polyline points={coords.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#bc6b3c" strokeWidth="3" strokeDasharray="8 5"/>{coords.map((p,i)=><g key={points[i].id}><circle cx={p.x} cy={p.y} r="16" fill="#173f35"/><text x={p.x} y={p.y+5} textAnchor="middle" fill="white" fontSize="14">{i+1}</text></g>)}</svg><ol className="map-legend">{points.map(a=><li key={a.id}>{a.name} <a href={`https://www.google.com/maps/search/?api=1&query=${a.snapshot.lat},${a.snapshot.lng}`} target="_blank" rel="noopener noreferrer">外部地圖</a></li>)}</ol><p className="fine">直線連線僅呈現順序。下方外部路線由地圖服務顯示，本網站不擷取路線或路況。</p>{points.slice(1).map((a,i)=><a className="route-link" key={a.id} target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/dir/?api=1&origin=${points[i].snapshot.lat},${points[i].snapshot.lng}&destination=${a.snapshot.lat},${a.snapshot.lng}&travelmode=transit`}>{i+1} 至 {i+2}：查看外部交通路線</a>)}</div>;}
